### PR TITLE
fix alignmemt of the speakers pictures

### PR DESCRIPTION
**Pull request by fadouaabdoul**
Trying to fix the issue n: 11.

### CODE REVIEW

**Review by timokonkwo — CHANGES_REQUESTED** [review]
Hi. This is a nice work. Please make the following changes and resubmit a PR

- Add the **.idea** folder to **.gitignore** so it won't be pushed along with your changes.
- In the styling of the img-speaker class you created, add `object-fit: cover;` in the CSS so the img will maintain its scaling despite the changes in width and height of its container.

When you effect the changes, please submit another PR

**Comment by fadouaabdoul** [comment]
Hello, Thank you for the review.
I will for sure try to make these changes and try to make another PR.

**Comment by fadouaabdoul** [comment]
Hello, here I did update the changes as you mention it in the first review. 
@timokonkwo

**Review by timokonkwo — APPROVED** [review]
Great job there!

**Pull request merged**
